schema_version: 1

context:
  version: "2.1.1"

package:
  name: vcs_versioning
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/v/vcs_versioning/vcs_versioning-${{ version }}.tar.gz
  sha256: 162749bbf8fa4a5db52330a7e61438cc1962033bab9f7c2d294d1078d40a4534

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - vcs-versioning = vcs_versioning._cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - packaging >=20
    - typing_extensions
    - pip
  run:
    - python >=${{ python_min }}
    - packaging >=20
    # Drop tomli dependency when conda-forge drops python 3.10.
    - tomli >=1
    - typing_extensions

tests:
  - python:
      imports:
        - vcs_versioning
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - vcs-versioning --help

about:
  summary: the blessed package to manage your versions by vcs metadata
  license: MIT
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/vcs-versioning/
  repository: https://github.com/pypa/setuptools-scm
  documentation: https://github.com/pypa/setuptools-scm

extra:
  recipe-maintainers:
    - tcompa
    - ocefpaf
